# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_auto_20151222_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='gestion',
            field=models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015)], unique=True, verbose_name=b'Gestion Academina'),
        ),
    ]
