# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0005_auto_20151203_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscripcion',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='materno',
            field=models.CharField(max_length=20, verbose_name=b'Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name=b'Nombres'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='paterno',
            field=models.CharField(max_length=20, verbose_name=b'Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name=b'Telefono/Celular'),
        ),
    ]
