# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20151203_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativo',
            name='cargo',
            field=models.CharField(max_length=50, verbose_name=b'Cargo Ocupado'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name=b'Direcci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=b'Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='materno',
            field=models.CharField(max_length=20, verbose_name=b'Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name=b'Nombres'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='paterno',
            field=models.CharField(max_length=20, verbose_name=b'Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name=b'Telefono/Celular'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.CharField(default=b'Estudiante', max_length=20),
        ),
    ]
