# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20160518_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativo',
            name='cargo',
            field=models.CharField(max_length=50, verbose_name='Cargo Ocupado'),
        ),
        migrations.AlterField(
            model_name='administrativo',
            name='nro_item',
            field=models.IntegerField(verbose_name='Numero de Item'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='carga_horario',
            field=models.PositiveIntegerField(default=1, help_text='En Horas', verbose_name='Carga Horaria Semanal'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nro_docente',
            field=models.IntegerField(unique=True, verbose_name='Item Docente'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nro_estudiante',
            field=models.IntegerField(unique=True, verbose_name='Codigo Estudiante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='avatar',
            field=models.ImageField(upload_to='avatar', verbose_name='Seleccione Una Imagen'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ci',
            field=models.CharField(max_length=10, unique=True, verbose_name='Cedula de Identidad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateField(validators=[usuarios.models.validate_fecha_nac], verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='materno',
            field=models.CharField(max_length=20, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='paterno',
            field=models.CharField(max_length=20, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Telefono/Celular'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.CharField(default='Estudiante', max_length=20),
        ),
    ]
