# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0005_inscripcion_terminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='nro_folio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
